### ISSUE TITLE
Idempotency during upgrade

### ISSUE THREAD

**Issue by kaushik229** [vmware/cluster-api-upgrade-tool#1]
Where possible we should attempt to introspect state from the underlying objects (such as the defined Kubernetes version). Where that is not possible, it might be a good idea to track the state using annotations (or a CRD) rather than storing state locally within the tool.

We need to add support for making sure cluster upgrades are idempotent.
In case of failure, we must start from the state where previous run of upgrade failed.

**Comment by chuckha** [comment]
Annotations along with the algorithm above seem to be a reasonable first approach, but it sounded like we might need a rethink here, any additional concerns I should know about @ncdc?

### Annotations as state machine
How is this not a library yet? It's out of scope right now but I've seen this idea come up a number of times and a library would be nice. I'm pretty ok starting out with the proposed algorithm above, or something very similar.

#### States
* Pending => upgrade has not started
* Started (Upgrading?) => upgrade is in the process of happening
* Finished => upgrade has finished (this state will be deleted almost immediately)
* No state => No known upgrade requests
* Error => Error was encountered during an upgrade. May require human intervention.

**Comment by ncdc** [comment]
I'm not sure it makes the most sense to use an annotation on the `Cluster` that is an enum `UpgradeAll | UpgradeControlPlane | UpgradeWorkers`. For upgrading workers (machine deployments), that is achieved by changing the kubelet version in the machine deployment spec. Therefore I don't think we need `UpgradeAll` or `UpgradeWorkers`. That leaves `UpgradeControlPlane`, but it doesn't contain enough information. I think I'd rather see something that indicates "desired control plane version", and our upgrade tool can evaluate that value against the version for each control plane machine (and possibly other annotation metadata) to determine what to do. That's my initial thought. Will add more soon.

**Comment by detiber** [comment]
@ncdc if we want a "no-op" type upgrade where we upgrade the cluster without upgrading the k8s version, we will need to trigger off of something more than just the k8s version.

**Comment by ncdc** [comment]
True, thanks for pointing that out. Will need to figure out how to define that as part of the "possibly other annotation metadata" 😄

**Comment by ncdc** [comment]
For same-version control plane machine replacements, we could have the upgrade tool generate a unique "control plane revision/id" and store that in an annotation. If a control plane machine does not also have that same annotation & value, we'd consider that machine stale and in need of replacement. We'd then create a new control plane machine (presumably taking advantage of a newer OS image) and make sure we annotate the machine with this "control plane revision/id".

For same-version MachineDeployment machine replacements, we could adjust a similar label or annotation in machineDeployment.spec.template.spec.metadata, maybe?

**Comment by chuckha** [comment]
For the machine deployment case we don't need to do anything to make this tool reentrant. Either this program will update the machine deployment or it will not. If it does update the machine deployment, the provider should manage the upgrade. This assumes we are deferring cordon & draining to each provider. If it does not update the machine deployment the user can run it again to try to update the machine deployment.

**Comment by detiber** [comment]
@chuckha I agree with your statement in theory, however in practice today I think there are two challenges that we need to address:

- To avoid unnecessary workload disruption we should likely not "re-upgrade" a MachineDeployment that has already been fully upgraded. For version-based upgrades this is not difficult, since it will be a true noop on the MachineDeployment, but for the "noop" upgrade case we need to make sure to only trigger the MachineDeployment update in the case it hasn't already been "upgraded"
- The lack of remote node references means that we'll likely have to track the status of the MachineDeployment upgrade externally somehow to determine the health of the MachineDeployment and if we potentially need to rollback.

**Comment by chuckha** [comment]
Agreed, the introduction of a new no-op upgrade feature would need to be tracked.

**Comment by chuckha** [comment]
## Control Plane Upgrade

* Create a token (using @ncdc's timestamp idea)
* Print out the token generated that will be used if a resume must happen
* when we spin up a new node we annotate each one with

```
"cluster-upgrade-id": "timestamp"
```

* If an upgrade dies in the middle we will have some nodes with an annotation and some without. Or no nodes with any annotation, or all nodes with annotation.
* We rerun the upgrade tool with a timestamp like `cluster-upgrade-tool --id <timestamp> ...<same arguments as initially used>` and we can figure out which nodes need to be acted upon and which do not (respectively, those without the ID annotation and those with)

## MachineDeployments
version upgrades are already ok
image upgrades will require the same technique as the control plane. I have to do some research to see how machineDeployments actually work, but this is independent of the control plane problem and I'll come back to this later.

**Comment by ncdc** [comment]
We have logic that uses a single annotation to keep track of an "upgrade ID". This is done.
