### ISSUE TITLE
Should we make this an always-on pod instead of a one-shot CLI?

### ISSUE THREAD

**Issue by ncdc** [vmware/cluster-api-upgrade-tool#10]
Title says it all. We almost have CRDs to use as inputs (the `upgrade.Config` structs). If we made this a pod with controller(s), it might be easier to track state. It's also a lot more work...

**Comment by detiber** [comment]
Personally, I would like to see us build the tool in a way that it can be consumed in the following order:
- as a library
- as a cli tool
- as a controller/operator

I think the controller/operator model introduces some particular challenges that will probably be easier to address once we have the base ad-hoc/single shot use case covered.

**Comment by ncdc** [comment]
SGTM. We've already got a library & cli tool. Adapting to controllers hopefully wouldn't be too bad.

**Comment by chuckha** [comment]
Closing since this is non-actionable right now.
