### ISSUE TITLE
stale kubeconfig secret

### ISSUE THREAD

**Issue by chuckha** [vmware/cluster-api-upgrade-tool#110]
When a load balancer is not used for the original kubeconfig secret, the kubeconfig secret becomes stale after an upgrade in the case of a single node control plane cluster.

We should update the endpoint of the kubeconfig secret or use the load balancer from the start.

**Comment by detiber** [comment]
This seems like something that we might need to handle in CAPI as part of the Cluster controller (as the APIEndpoints are updated).

**Comment by ncdc** [comment]
I'm in favor of not making this something the upgrade tool needs to worry about unless there's significant demand. Would that be ok, @chuckha?

**Comment by chuckha** [comment]
sgtm
