### ISSUE TITLE
config file vs command line flags

### ISSUE THREAD

**Issue by chuckha** [vmware/cluster-api-upgrade-tool#111]
with the addition of #104 we will be accepting config files in addition to command line flags.

It is a bit ambiguous how these two user supplied fields will interact with each other.

I suggest having the command line flags override the config file. The reason for this is that sometimes it's nice to use the same config with stuff I don't want to manually type in but override just a single field, such as version. Whatever the implementation, I'd like to avoid defining a complex precedence order.

**Comment by ncdc** [comment]
I'm fine with a follow-up PR that has the command line flags override config file values.
