### ISSUE TITLE
repaving feature

### ISSUE THREAD

**Issue by chuckha** [vmware/cluster-api-upgrade-tool#13]
This is a no-op upgrade from the kubernetes perspective, as in, the version won't change but all the nodes will get cycled and perhaps a new underlying image is used, or not, but the nodes will be destroyed and recreated without kubernetes version changing.

Imagine a kernel security bug. Kubernetes version doesn't have to change but os versions should be bumped.

Note: this may be the wrong usage of the term repaving, but that's fine.

**Comment by ncdc** [comment]
Once MachineDeployment upgrade-id support is in, this can be closed.

**Comment by ncdc** [comment]
This has been implemented.
