### ISSUE TITLE
Adding control plane machine(diff. k8s ver) to an already existing cluster fails 

### ISSUE THREAD

**Issue by bhargavmad** [vmware/cluster-api-upgrade-tool#132]
/kind bug

**What steps did you take and what happened:**
1. Create workload cluster with a single control-plane machine (k8s ver: 1.15.3)
2. Deploy CNI
3. Create a machinedeployment(k8s ver: 1.16.0) with 2 replicas
4. Now, Create a new control-plane machine(k8s ver: 1.15.3)

**Output:**
* New control-plane machine instance created but did not join the cluster
* Machine status = provisioned

**What did you expect to happen:**
* Control-plane machine to be part of the cluster
* Machine status = running

**Remarks:**
I have seen in the logs that the bootstrap join config ran, but somehow it doesn't actually join the cluster. When I try the same steps with same k8s versions on both control-planes and machinedeployments there seems to be no error. Also, when I created the 2nd control-plane machine before the machinedeployment everything works fine (different k8s versions)

**Comment by ncdc** [comment]
Hi @bhargavmad, it is not valid or supported to have worker nodes using a newer minor version compared to the control plane. In other words, with a control plane running v1.15, you may not run workers at v1.16.

Do you have the cloud-init output from the new control plane machine?

Could you please retest the scenario above with a MachineDeployment running v1.15?

**Comment by bhargavmad** [comment]
Hi @ncdc, when I created 2 control-plane machines with v1.15 and then added a MachineDeployment with v1.16, everything worked fine. So in that case, I assume there shouldnt be any error when adding the control-plane at a later stage.

I do not have the cloud-init output now. but can reproduce and get it.

I tested MachineDeployment with v1.15 and there were no errors.

**Comment by ncdc** [comment]
> So in that case, I assume there shouldn't be any error when adding the control-plane at a later stage.

There shouldn't be any issues, but I'd like to avoid troubleshooting unsupported configurations if possible.

Please try to reproduce with everything on 1.15 and capture as much output/logs as possible. Thanks!

**Comment by bhargavmad** [comment]
> 
> There shouldn't be any issues, but I'd like to avoid troubleshooting unsupported configurations if possible.
>
Got it.
> 
> Please try to reproduce with everything on 1.15 and capture as much output/logs as possible. Thanks!
>
No problem here.

Closing the issue.

**Comment by ncdc** [comment]
👍 - please reopen if/when you reproduce!
