### ISSUE TITLE
Upgraded machine hostnames are resolving as FQDNs

### ISSUE THREAD

**Issue by andrewsykim** [vmware/cluster-api-upgrade-tool#138]
When upgrading a control plane machine, my cluster lost quorum because the new and old machine had the same hostname (which is eventually read by etcd as the member name). Because upgraded machines have the format `<old-machine-name>.upgrade.<upgrade-id>`,  [Cloud Init is interpreting the hostname as an FQDN](https://github.com/canonical/cloud-init/blob/0469f70c8fde69cfbcbc7181a69964aafba50bbc/cloudinit/sources/__init__.py#L555-L614) and resolving the hostname only up to the first "." of the machine name. As a result, the hostnames conflict between the previous and new machine. 

I was able to manually work around this by replacing `.upgrade.<upgrade-id>` to `-upgrade-<upgrade-id>`. Would there be any drawbacks to using this new format? 

more details here: https://github.com/vmware/cluster-api-upgrade-tool/issues/136

**Comment by ncdc** [comment]
There are no drawbacks that I can think of. Alternatively, should we consider removing the forced `.upgrade.` or `-upgrade-` snippet entirely?
