### ISSUE TITLE
kubelet version is never upgraded because machine image is not updated

### ISSUE THREAD

**Issue by andrewsykim** [vmware/cluster-api-upgrade-tool#139]
Based on my understanding of the image-builder, the kubelet version is fixed and not updated based on the version set in the Machine resource. As a result, running the upgrade tool never upgrades the kubelet version on control planes because we don't update the machine image in the infrastructure ref resource. 

Should the upgrade-tool have a flag or something that accepts the new machine image we should be using?

related: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/635

**Comment by andrewsykim** [comment]
@codenrhoden can you confirm that the kubelet is not updated for all providers, not just CAPV?

**Comment by ncdc** [comment]
We do 2 things to address the Kubernetes version:

1. For the control plane (static pods), we update the kubeadm-config ConfigMap to change the version
2. We allow you to change the image ID (see the patches part of https://github.com/vmware/cluster-api-upgrade-tool#specify-options-with-a-config-file)

**Comment by ncdc** [comment]
Also, some providers, such as CAPA, do image ID lookups based on machine.spec.version, if the image ID is unset (in the provider-specific resource)

**Comment by andrewsykim** [comment]
Ah I missed that, thanks @ncdc!
