### ISSUE TITLE
kubeadm configmap cluster status api endpoints sync code is buggy

### ISSUE THREAD

**Issue by ncdc** [vmware/cluster-api-upgrade-tool#141]
The code currently reconciles between Nodes in the workload cluster and Machines. If it finds a Node that is being deleted or doesn't have a matching Machine, it removes the entry from the map. This is fine for Nodes that still exist... but if both the Node and its associated Machine have been deleted, this logic makes it impossible to remove an entry for this Node from the ConfigMap if it's still there for whatever reason.

A better alternative could be to remove all entries from the ConfigMap where this is not a Node with a matching name. The entry in the map is the Node's name, so this is a 1:1 mapping. This is predicated on node bootstrapping doing the following:

1. `kubeadm join` runs
    1. Node is registered in etcd
    1. ConfigMap is updated with new Node

If this is the sequence, we are good. If, however, the ConfigMap is updated first, there is a chance for a race condition where the entry exists in the ConfigMap, there is no Node in etcd yet, and the upgrade tools runs and reconciles the data, removing the entry from the map because it doesn't see a corresponding node.

cc @fabriziopandini - let's chat about this next week!

**Comment by fabriziopandini** [comment]
Sure!

The sequence in kubeadm is:  1. start kubelet 2. create the etcd static pod manifest, 3. wait for the etcd member, 4. update the config map
The tricky part is that Kubelet is responsible for generating the node object, not kubeadm, so there is no hard check encoded in kubeadm that the node is generated before the config map is updated.
