### ISSUE TITLE
Upgrade completes successfully but fewer masters than expected

### ISSUE THREAD

**Issue by williamsandrew** [vmware/cluster-api-upgrade-tool#149]
Our team is seeing an occasional issue where an upgrade completes successfully according to the upgrade tool but when you look at the `kubectl get node` output there will be fewer master nodes than expected. This appears to be related to `kubeadm` failing at the Etcd step. See below:

```
[etcd] Announced new etcd member joining to the existing etcd cluster
[etcd] Creating static Pod manifest for "etcd"
[etcd] Waiting for the new etcd member to join the cluster. This can take up to 40s
{"level":"warn","ts":"2020-02-06T18:06:40.249Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"passthrough:///https://10.0.3.21:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[kubelet-check] Initial timeout of 40s passed.
error execution phase control-plane-join/etcd: error creating local etcd static pod manifest file: timeout waiting for etcd cluster to be available
To see the stack trace of this error execute with --v=5 or higher
Feb 06 18:09:35 cloud-init[4206]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd [1]
Feb 06 18:09:35 cloud-init[4206]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Feb 06 18:09:35 cloud-init[4206]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Cloud-init v. 19.3-2.amzn2 finished at Thu, 06 Feb 2020 18:09:35 +0000. Datasource DataSourceEc2.  Up 227.89 seconds
```

However, the upgrade tool continues onto the next node despite this failure. If you look at the attached log output, it *does* appear that the new Etcd member joined the cluster despite the Deadline above.

Here is the out of `kubectl get nodes` on this cluster. The "ip-10-0-3-21.ec2.internal" is supposed to be the 3rd master node.

```
$ kubectl get nodes
NAME                         STATUS   ROLES    AGE   VERSION
ip-10-0-1-18.ec2.internal    Ready    <none>   21h   v1.16.4+vmware.1
ip-10-0-1-207.ec2.internal   Ready    master   21h   v1.16.4+vmware.1
ip-10-0-3-21.ec2.internal    Ready    <none>   21h   v1.16.4+vmware.1
ip-10-0-5-23.ec2.internal    Ready    master   21h   v1.16.4+vmware.1
```

[logs.txt](https://github.com/vmware/cluster-api-upgrade-tool/files/4171540/logs.txt)

**Comment by ncdc** [comment]
What currently happens is that the status of machine bootstrapping (cloud-init, in this case) is entirely ignored, unfortunately. Instead, it's just "hope for the best". And, again unfortunately, what can happen is the `kubeadm join` call can:

1. Fail badly enough such that no node is registered
1. Fail in some manner, such as above, but the node is still registered (although it's possible not all of the `kubeadm join` steps completed, such as labeling the node)
1. Succeed

One thing @williamsandrew & I discussed was the possibility to determine that `kubeadm join` had definitively succeeded, without need shell access to the machine. One possible approach would be to have the very last step of `kubeadm join` label or annotate the node with a well know "kubeadm is all done" marker. The upgrade tool could wait up to a timeout for that to appear. If it doesn't appear, the upgrade tool would then need to perform all the logic to delete the machine (including possibly removing the member from etcd and the kubeadm configmap), and then attempt to create another replacement.

In the future, CAPI infra providers must detect bootstrapping failures and be able to report them in a consistent manner, but we're not there yet.

**Comment by fabriziopandini** [comment]
I see two potential problems here
1. Understand why kubeadm fails 
2. Properly detect an error and handle it 

Wrt to 1. Understand why kubeadm fails the error is generated because the kubelet healthz did not provided answer in 40 seconds after starting the service. 
According to the issue this timeout seems too aggressive, because at the end the node get created, so one option is to increase the timeout to 60/90 seconds.

**Comment by ncdc** [comment]
The upgrade tool does check the readiness of the control plane pods on the new machine, and it also checks overall etcd health at the beginning of processing each control plane machine. If the upgrade "succeeds", it means that all the pods are good, and etcd is good. This can still happen even if cloud-init "fails", as we've seen above...

**Comment by vincepri** [comment]
Could we add a `trap` (like in bash) to the cloud-init code so that if anything fails, we make sure to run `kubeadm reset` or something similar to make sure the node doesn't join?

**Comment by ncdc** [comment]
xref https://github.com/kubernetes/kubernetes/issues/87961#issuecomment-584183616 re cloud-init `runcmd` & failures

**Comment by detiber** [comment]
> Could we add a trap (like in bash) to the cloud-init code so that if anything fails, we make sure to run kubeadm reset or something similar to make sure the node doesn't join?

possibly...  I'm wondering if we should just go ahead and `halt` the instance instead, though... That way it would translate into a FailureMessage/FailureReason pretty easily

**Comment by ncdc** [comment]
"we" being the infra provider?

**Comment by detiber** [comment]
"we" being the bootstrapping provider, assuming we can wrangle a trap to be effective for the `runcmd` entries we are setting.

**Comment by ncdc** [comment]
If it's a control plane machine, we have to be careful in v1alpha2, since we can get into a situation where cloud-init "fails" but the machine joins etcd. We can't just halt in that case, can we? (And presumably we'd need to do the same for v1a3).

**Comment by detiber** [comment]
It's definitely a tricky situation...  We can break things if we continue letting the machine run as normal on failure, but we can also break things if we try to cleanup (either through `kubeadm reset` or `halt`). 

> One thing @williamsandrew & I discussed was the possibility to determine that kubeadm join had definitively succeeded, without need shell access to the machine. One possible approach would be to have the very last step of kubeadm join label or annotate the node with a well know "kubeadm is all done" marker. The upgrade tool could wait up to a timeout for that to appear. If it doesn't appear, the upgrade tool would then need to perform all the logic to delete the machine (including possibly removing the member from etcd and the kubeadm configmap), and then attempt to create another replacement.

We could definitely take a step similar to this, however it would only be applicable to Control Plane Machines, since worker Machines would not have the appropriate credentials to set labels on their own Node resource outside of what is available in the Kubelet configuration for initial labels.
