### ISSUE TITLE
Support for Upgrades to Kubernetes 1.18

### ISSUE THREAD

**Issue by DheerajSShetty** [vmware/cluster-api-upgrade-tool#167]
cluster-api-upgrade-tool needs to backport the fix for the issue mentioned here.
https://github.com/kubernetes-sigs/cluster-api/issues/2793

Link to the fix 
https://github.com/kubernetes-sigs/cluster-api/pull/2968

**Comment by ekj1711** [comment]
Shall I give it a try?

**Comment by ncdc** [comment]
@ekj1711 if you have time, that'd be great!

**Comment by ncdc** [comment]
If not, please let me know, and I'll find someone else to work on it. Thanks.

**Comment by ekj1711** [comment]
I am getting the following error while trying to raise a review. 

ejohn-a01:cluster-api-upgrade-tool ejohn$ git push origin ejohn/support-upgrade
ERROR: Permission to vmware/cluster-api-upgrade-tool.git denied to ekj1711.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by ncdc** [comment]
You have to fork the repo, push to your fork, and open a PR from there against this repo
