### ISSUE TITLE
support provider IDs from various providers

### ISSUE THREAD

**Issue by chuckha** [vmware/cluster-api-upgrade-tool#35]
This looks pretty hardcoded right now to do something pretty specific

**Comment by ncdc** [comment]
We need to follow the lead from Vince's work on the CAPI NodeRef controller (not merged yet) - https://github.com/kubernetes-sigs/cluster-api/pull/1011/files#diff-2e940bebe0dee1f181c0176d34f4bc8c

**Comment by ncdc** [comment]
Vince's code has merged - https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/controller/noderefutil/providerid.go has what we need (and it's in the `release-0.1` branch).

**Comment by ncdc** [comment]
We should replace this repo's `ParseProviderID` function and use the one from CAPI

**Comment by chuckha** [comment]
closed by #62
