### ISSUE TITLE
Document how to upgrade a managment cluster with this tool

### ISSUE THREAD

**Issue by detiber** [vmware/cluster-api-upgrade-tool#43]
Currently there are known issues when trying to upgrade a management cluster with cluster-api-upgrade-tool. We should document the process.

Ideally we'd be able to handle it within the tool itself, but a potential manual process could be:
- `clusterctl alpha phases pivot` to a temporary cluster
- upgrade management cluster using `cluster-api-upgrade-tool`
- `clusterctl alpha phases pivot` back to management cluster

**Comment by ncdc** [comment]
@detiber I can't think of specific issues that would keep this tool from being able to upgrade a management cluster - could you elaborate?

**Comment by ncdc** [comment]
Cluster API v1alpha3 has KubeadmControlPlane and it's able to upgrade a self-hosted management cluster. Not planning on doing this.
