### ISSUE TITLE
Split upgrade tool into actions & runner

### ISSUE THREAD

**Issue by chuckha** [vmware/cluster-api-upgrade-tool#46]
## Split upgrade into actions and have upgrader call the appropriate actions

Upgrade should become a runner of actions, just like kubeadm and other "phased" command line tools. I don't think we should expose them via the command line however, they should only be available via the public API. If we expose them through the command line we *significantly* complicate the user experience, which, with all the flags we have, is complicated enough and there is no current use case for exposing individual actions to users.

The reason I want to do this is because it's impossible to test the idempotency work without being able to stop the upgrade at an exact time (easily). We could pass a context in at the top level and use a timeout, but there are no guarantees at what point the upgrade will be in after the timeout. Alternatively we could have a process watch, wait for conditions on the cluster then kill the process, but that is a race condition. 

To make this tool completely hardened/testable we need to be able to control exactly when it stops to account for various scenarios.

## Proposal of actions

1. Create new machine with functional options: wait for provider id, wait for node with matching provider id, wait for node to be ready

```
func (u *Upgrader) CreateNode(*machine, ...func()) error {...}
CreateNode(&machine, WaitForProviderID, WaitForMatchingNode, WaitForNodeReady)
```

2. Delete etcd member (sidenote: we have a bug here where the kubeadm configmap isn't updated properly. we must use kubeadm reset on the node. kubeadm 1.15 makes this much easer)
3. Delete machine
4. Apply annotation

**Comment by ncdc** [comment]
I'm 100% in favor of this, thanks for writing it up!

**Comment by ncdc** [comment]
Talked to Chuck; decided not to do this.
