### ISSUE TITLE
Automated tests on PRs

### ISSUE THREAD

**Issue by chuckha** [vmware/cluster-api-upgrade-tool#48]
We should run tests and gofmt and such on PRs.

vmware may have a solution for us, but this issue is about investigating.

**Comment by ncdc** [comment]
We now run automated tests in Travis. This is just unit & verifications, but not integration/e2e (deploy a cluster & upgrade it).

**Comment by ncdc** [comment]
Travis is good enough. When we move this code into CAPI v1alpha3, we'll use prow to do real e2es too.
