### ISSUE TITLE
Upgrade of add-ons within the workload cluster

### ISSUE THREAD

**Issue by zjs** [vmware/cluster-api-upgrade-tool#49]
This issue will use terminology from the [Cluster API data model proposal](https://docs.google.com/document/d/1I2jieYq3DGJqRcThj-P3n-PrIL77OVjFbRgTwTj-sPg/edit):
> **Core Add-ons**: Addons that are required to deploy a Kubernetes-conformant cluster: DNS, kube-proxy, CNI, CSI.
> **Additional Add-ons**: Addons that are not required for a Kubernetes-conformant cluster (e.g. metrics/Heapster, Dashboard).
> ...
> **Workload cluster**: A cluster whose lifecycle is managed by a Management cluster.

With the Cluster API Upgrade Tool, how will upgrade of core and additional add-ons be handled?

Hypothetical:
1. I'm using a Cluster API provider which deploys "golden" VM images, which include the container images for all of the components which run in the workload cluster (e.g., so that creating a workload cluster from an air gapped environment is possible).
2. I'm running Kubernetes 1.15.0 and one or more add-ons. For simplicity, perhaps I'm using only a single core add-on: Calico v3.7.1.
3. I want to upgrade to Kubernetes 1.15.1. My Kubernetes 1.15.1 image contains Calico v3.7.3.
4.  At the beginning of the upgrade, I'm going to have a `DaemonSet` specifying `calico/*:v3.7.1` containers. The old nodes are going to have the corresponding `calico/*:v3.7.1` images. However, the new nodes are only going to have `calico/*:v3.7.3` images.

Concern:
* If I update the `DaemonSet` at the beginning of the upgrade, I have a problem: my old nodes don't have the container images for the new Calico version.
 * If I update the `DaemonSet` at the end of the upgrade, I have a different problem: my new nodes don't have the old Calico version, so Calico isn't running until the `DaemonSet` is upgraded.

Is there a convention for ensuring Calico (and all of my other core and additional add-ons) are properly handled during this rolling upgrade? Perhaps different conventions are needed for different sorts of add-ons.

Excuse my ignorance here; I haven't tried to use the Cluster API Upgrade Tool yet and may be missing something obvious.

**Comment by detiber** [comment]
CNI and CSI providers are a bit tricky in this regard. As far as kubeadm is concerned it is not a "core" add-on, so there is no native support there (compared to CoreDNS, and kubeproxy addons). The ordering of applying the updates may very well depend on the CNI or CSI provider.

For Calico in particular, it should be okay to initiate the CNI add-on update either before or after the Cluster has been upgraded. As long as the cluster is not running in a disconnected environment, things should function normally across both sets of images (although Nodes with mismatched container versions will take longer to reach the Ready state).

**Comment by zjs** [comment]
Hi @detiber, thanks for the quick response. Do you have any thoughts on handling the cases where a new node can't easily pull the old add-on's container image? (E.g., a cluster running in an air-gapped environment, a cluster configured not to pull new container images onto control plane nodes, or a proprietary add-on not generally available.)

**Comment by ncdc** [comment]
I'd say the OS image would need to contain both old and new container image versions, to support straddling during the upgrade. Or you'd need to find a way to upgrade the addons in live machines first, so the cluster is prepared to use the newer version before you start the upgrade process.

**Comment by chuckha** [comment]
The way kubeadm handles air gapped environments is to list out all the images required to run `kubeadm init/join` so that users can get those images before moving to an offline environment.

The upgrade-tool proves to be a harder problem since, unless we maintain a list in this repo, we'd have to use the internet to find out what the next version is for each add on.

I'll definitely keep thinking about this, but right now I'm leaning towards what @ncdc has said.

**Comment by zjs** [comment]
> I'd say the OS image would need to contain both old and new container image versions, to support straddling during the upgrade.

I think this becomes unwieldy. The v1.15.1 image would need to include the add-on versions for all versions from which it supports upgrading. To support upgrade from v1.14.x and v1.15.0 could mean supporting 5 old versions of each add-on.

**Comment by ncdc** [comment]
Perhaps. You could ask people to upgrade to the latest 1.14.x before going to 1.15.0, and then you only have 1 image that has to have 2 add-on versions in it (1.15.0). But that might be onerous.

Do you have any other ideas that would make this cleaner?

**Comment by ncdc** [comment]
Circling back to this, I don't think this is something we can or should solve with the upgrade tool. Ideally, an add-on should work with Kubernetes _n_ and _n+1_. If not, it's probably a situation that will require more careful upgrade sequencing.

**Comment by chuckha** [comment]
Agreed. Will add-on upgrades be managed by the add-ons operator?

**Comment by ncdc** [comment]
Maybe? Managed by "something other than the upgrade tool" 😄
