### ISSUE TITLE
Node cordoning & draining

### ISSUE THREAD

**Issue by ncdc** [vmware/cluster-api-upgrade-tool#5]
We ideally should cordon and drain both control plane and worker nodes before deleting them. We can probably coordinate this in the upgrade tool directly for control plane nodes. Worker nodes are trickier, because we only support MachineDeployment-based worker nodes, and we don't have any easy direct way to effectively add a pre-delete hook to a Machine (that belongs to a MachineSet & MachineDeployment).

**Comment by chuckha** [comment]
As discussed earlier today we can for now improve the providers to do cordon & drain on delete.

https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/749

Here is some partial work for the aws provider.

**Comment by ncdc** [comment]
This is being added to cluster-api in https://github.com/kubernetes-sigs/cluster-api/pull/1103. Once that merges and a new 0.1.x release is out, that will be required for cordon/drain as part of machine deletion. Therefore I am closing this.
