### ISSUE TITLE
bring in some simple validation scripts

### ISSUE THREAD

**Issue by chuckha** [vmware/cluster-api-upgrade-tool#58]
@neolit123 has been doing amazing work porting around some verify scripts to new sig-cluster-lifecycle repos. They are extremely handy and should be run as part of an automated test.

It would be fantastic to get those merged into this repo as well.

**Comment by ncdc** [comment]
@chuckha can you point to which scripts you'd like pulled in?

**Comment by chuckha** [comment]
The full list is here https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/tree/master/hack

But we could get away with some automated running of gofmt or govet. This can close if it moves into Cluster API.

**Comment by ncdc** [comment]
Given our plan to sunset this repo once we move CAPI to v1alpha3, I'm in favor of closing. That ok with you?

**Comment by chuckha** [comment]
works for me!
