### ISSUE TITLE
Update kubeadm configmap

### ISSUE THREAD

**Issue by chuckha** [vmware/cluster-api-upgrade-tool#59]
When we remove a node we should remove it from the kubeadm config or risk etc attempting to contact a no longer responsive endpoint.

**Comment by chuckha** [comment]
cc @rudoi

He is seeing that there is a control plane that gets removed from the cluster but not from the config manager. Since it's the first one it is being used by kubeadm to contact the etcd server.

**Comment by rudoi** [comment]
Yep, can confirm, 2nd node's journal:

```
[check-etcd] Checking that the etcd cluster is healthy
error execution phase check-etcd: error syncing endpoints with etc: context deadline exceeded
```

At this point in the process, there should be 3 etcd members. However, there are 4 apiserver endpoints in the kubeadm configmap.
