### ISSUE TITLE
Assume an in cluster configuration if `--kubeconfig` is not specified

### ISSUE THREAD

**Issue by williamsandrew** [vmware/cluster-api-upgrade-tool#70]
In cases where you are running the upgrade tool from the management cluster itself, it would be nice if the tool would use credentials from the service account. In client-go speak, using `InClusterConfig()` as opposed to specifying a file in the filesystem.

The workaround at the moment is creating a Configmap/Secret and mounting it into the upgrade pod. This works but is not ideal.

**Comment by ncdc** [comment]
Our code should fall back to ICC if you don't specify the kubeconfig flag. If the flag is required, we should make sure everything works by making it optional, and do a PR for the change.
