### ISSUE TITLE
Machines are not cleaned up on failure causing extra control plane/etcd members

### ISSUE THREAD

**Issue by williamsandrew** [vmware/cluster-api-upgrade-tool#79]
If an upgrade fails after a machine is created, the machine is not cleaned up and may ultimately join the cluster. Attaching logs from four upgrade attempts on a three node control plane cluster. Ultimately I ended up with an etcd cluster that had 6 members. I unfortunately lost the output of `kubectl get nodes` due to a laptop restart but there were also >= 6 control plane nodes.

Attaching all of the logs but example is below:

```
time="2019-09-19T23:13:33Z" level=info msg="Updating provider IDs to nodes"
time="2019-09-19T23:13:33Z" level=info msg=deleteEtcdMember
time="2019-09-19T23:13:37Z" level=info msg="etcdctl stdout: "
time="2019-09-19T23:13:37Z" level=info msg="etcdctl stderr: Error: member ID is not provided\n"
Error: unable to delete old etcd member : command terminated with exit code 128
command terminated with exit code 128
github.com/vmware/cluster-api-upgrade-tool/pkg/internal/kubernetes.PodExec
        /workspace/pkg/internal/kubernetes/pod_exec.go:63
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).etcdctlForPod
        /workspace/pkg/upgrade/control_plane.go:525
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).deleteEtcdMember
        /workspace/pkg/upgrade/control_plane.go:469
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).updateMachines
        /workspace/pkg/upgrade/control_plane.go:307
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).Upgrade
        /workspace/pkg/upgrade/control_plane.go:101
main.upgradeCluster
        /workspace/main.go:114
main.main.func1
        /workspace/main.go:37
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main
        /workspace/main.go:82
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
unable to delete old etcd member
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).updateMachines
        /workspace/pkg/upgrade/control_plane.go:309
github.com/vmware/cluster-api-upgrade-tool/pkg/upgrade.(*ControlPlaneUpgrader).Upgrade
        /workspace/pkg/upgrade/control_plane.go:101
main.upgradeCluster
        /workspace/main.go:114
main.main.func1
        /workspace/main.go:37
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main
        /workspace/main.go:82
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```

Etcd members:
```
$ k exec -ti -n kube-system etcd-ip-10-0-3-111.us-west-2.compute.internal -- etcdctl --ca-file=/etc/kubernetes/pki/etcd/ca.crt --key-file=/etc/kubernetes/pki/etcd/peer.key --cert-file=/etc/kubernetes/pki/etcd/peer.crt --endpoints=https://127.0.0.1:2379 cluster-health
member 3285a671bb2f9595 is healthy: got healthy result from https://10.0.5.84:2379
member 5ed3ed67c9a1e4e3 is healthy: got healthy result from https://10.0.5.239:2379
member c2c953e2269e5dab is healthy: got healthy result from https://10.0.5.55:2379
member c6d9414aef83f711 is healthy: got healthy result from https://10.0.5.120:2379
member f051abf97498a9af is healthy: got healthy result from https://10.0.1.123:2379
member fd3298bb7c4dd093 is healthy: got healthy result from https://10.0.3.111:2379
cluster is healthy
```

[pod_phase1-ajw3-6plzz-logs.txt](https://github.com/vmware/cluster-api-upgrade-tool/files/3687044/pod_phase1-ajw3-6plzz-logs.txt)
[pod_phase1-ajw3-tfblx-logs.txt](https://github.com/vmware/cluster-api-upgrade-tool/files/3687045/pod_phase1-ajw3-tfblx-logs.txt)
[pod_phase1-ajw3-w24qh-logs.txt](https://github.com/vmware/cluster-api-upgrade-tool/files/3687046/pod_phase1-ajw3-w24qh-logs.txt)
[pod_phase1-ajw3-zlrcz-logs.txt](https://github.com/vmware/cluster-api-upgrade-tool/files/3687047/pod_phase1-ajw3-zlrcz-logs.txt)

**Comment by ncdc** [comment]
We may need to do something like this:

1. Given an existing control plane machine, `M0`
1. Prepare its replacement machine, `M1` (but don't create it yet)
1. Mark the original `M0` as being replaced (annotation? in some more detailed configmap?) by `M1`
1. Create `M1`
1. Wait for node associated with `M1` to be ready
1. Delete `M0` from etcd

This way, if we fail in various places, we should be able to pick back up where we left off correctly:
1. If we marked `M0` as being replaced by `M1` but we never created `M1` for some reason, we can pick up here and create `M1`
1. If we created `M1` but we failed to delete `M0` from etcd, we can resume this task

Does something like this make sense? cc @chuckha @amy @rudoi

**Comment by ncdc** [comment]
If we do something like this, we may need to rethink our algorithm of "loop through machines and do steps 1-n"

**Comment by chuckha** [comment]
suggested annotation: `vmware.upgrade-tool/replaced-by: <machine-name (m1)>`

Regardless of new algorithms we should make removing a machine idempotent in this case so we can rerun that logic on failed attempts if it's not already (i think it is but we should double check).

We might need more state thinking about it though. Something to keep track of the state of the upgrade on each control plane node (success or failure). Something like "calculate the state of the world, find the node(s) with failed upgrade attempts. attempt to complete those upgrades, after those complete, do the rest of the nodes that are not marked as completed"

This sounds so much like a controller 😞

**Comment by randomvariable** [comment]
Just a note that creating then deleting isn't recommended in the etcd docs, so maybe able to reduce some of this tracking? https://github.com/etcd-io/etcd/blob/master/Documentation/faq.md#should-i-add-a-member-before-removing-an-unhealthy-member

**Comment by detiber** [comment]
@randomvariable the docs you link are for the case where the member to be removed is unhealthy. I don't think there is a strong recommendation when adding a new member to replace an already healthy member.
