### ISSUE TITLE
Make new machine names configurable 

### ISSUE THREAD

**Issue by amy** [vmware/cluster-api-upgrade-tool#81]
https://github.com/vmware/cluster-api-upgrade-tool/pull/72/files#r331532807

Currently the machine names are set like this `name := fmt.Sprintf("%s-%s-%d", nameParts[0], nameParts[1], time.Now().Unix())`.

**Comment by ncdc** [comment]
Instead of making the names configurable, I've taken a different approach in #100. We take the existing name and append `.upgrade.<upgrade ID>`, making sure not to exceed the maximum allowed length allowed by the API server (253 characters).
