### ISSUE TITLE
Fix integration tests to work

### ISSUE THREAD

**Issue by amy** [vmware/cluster-api-upgrade-tool#84]
The integration tests for the cluster upgrade tool that will run against v1alpha2 fail. The upgrade tool is manually verified.

**Comment by amy** [comment]
Integration tests should cover:
- upgrading control plane & worker nodes consecutively
- upgrading control plane independently
- upgrading worker nodes independently
- upgrading control plane & worker nodes consecutively twice
- upgrading HA control plane

**Comment by ncdc** [comment]
Fixed by #117
