### ISSUE TITLE
apiserver pod for removed etcd member remains, potentially causing subsequent machine deletion to fail

### ISSUE THREAD

**Issue by rudoi** [vmware/cluster-api-upgrade-tool#96]
So the current flow per controlplane machine is, simplified:
1. remove etcd member
2. delete Machine

Technically, between those two steps, there is an instance still being targeted by the ELB that does not have etcd behind it. API Server requests made that would be routed to this apiserver instance will time out. Sometimes the delete machine call (step 2) fails because of this.

Possible things:
1. delete the apiserver pod on the old node before removing the etcd member
2. wait for ELB to declare instance unhealthy (how?)

Additionally:
1. per discussion with @chuckha, there may be some CAPA fixes involved here: should CAPA ensure ELB targets are removed when controlplane Machines are deleted?

cc @amy

**Comment by ncdc** [comment]
Would the ideal flow, if we can make it happen, be this?

For an original machine _O_, and its replacement machine _R_

1. Create _R_
    1. _R_ is added to the load balancer
1. Remove _O_ from the load balancer
1. Remove _O_'s etcd member from the etcd cluster
1. Delete _O_

**Comment by ncdc** [comment]
We don't have much flexibility to remove _O_ from the load balancer in v1alpha2 before deleting the machine. I think at this point, the best recourse is to retry machine deletion over a period of maybe 3 minutes.
