### ISSUE TITLE
Add support for adjusting fields in referenced infra and bootstrap objects for control plane machines

### ISSUE THREAD

**Issue by ncdc** [vmware/cluster-api-upgrade-tool#99]
We added code originally to be able to modify the ID of a Machine's image (AMI/OVA/etc), in case the user wanted to specify the ID rather than letting the provider choose it based on the Kubernetes version.

With the conversion to only support CAPI v1alpha2, the image field is no longer part of the providerSpec blob in the Machine spec. If one exists, it's now in the infrastructure provider's machine resource (e.g. `AWSMachine`, for CAPA). The code we have doesn't work any more, since it still acts against the Machine for modifying the image.

Do we still need to be able to specify the Machine's image ID when doing an upgrade? If so, we'll need to adjust the code to mutate the object referenced by Machine.Spec.InfrastructureRef.

**Comment by zjs** [comment]
I think the separation between infrastructure and bootstrap provider configuration in v1alpha2 complicates this.

I think the Cluster API provider I work on now has three things that need to be kept in sync:
1. The Machine `.Spec.Version`.
2. The `imageRepository` and `imageTag` fields of the `KubeadmConfig`.
3. An image identifier in the infrastructure configuration.

At least the second requirement may go away when https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/131 is addressed.

Addressing that issue may also, indirectly, allow the third requirement to be addressed by teaching the infrasturcture provider to resolve a `.Spec.Version` into an image identifier.

**Comment by ncdc** [comment]
Is the value of Machine `.Spec.Version` always the same as `imageTag`? Or do we need to make it possible to mutate both in this tool?

For an upgrade scenario, I think we can safely assume `imageRepository` is already valid on an existing `Machine` or `MachineDeployment` and we don't need to mutate it at all?

Issue 131 won't be resolved for v1alpha2 - it may be for v1alpha3 or later.

**Comment by ncdc** [comment]
Had a chat with members from @zjs's team. They need to be able to manipulate multiple fields on their infra machine and the kubeadm bootstrap config. We should add a generic mechanism for an arbitrary number of (field path, new value) changes for each object.

**Comment by zjs** [comment]
> We should add a generic mechanism for an arbitrary number of (field path, new value) changes for each object. Such as (for KubeadmConfig) `spec.clusterConfiguration.dns.imageTag=my-new-version`.

Just an idea: perhaps this generic mechanism could take a jsonpatch (e.g., `[{"op": "replace", "path": "/spec/clusterConfiguration/dns/imageTag", "value": "my-new-version"}]`) for the bootstrap config and the infrastructure config.

I don't know of a use case that requires this added flexibility, but it may be useful to someone else, and may be an easy format for the upgrade tool to consume.

**Comment by ncdc** [comment]
`cluster-api-upgrade-tool --machine-infra-patch STRING --machine-bootstrap-patch STRING`?

There are multiple fields that need to be modified, so it seemed easier to me to accept a list of patches (either my simplified format, or jsonpatch) vs. singling out each field as its own flag/config option. WDYT?

**Comment by chuckha** [comment]
those are patches in the actual command line like

`tool --machine-infra-patch '[{"op": "replace", "path": "/spec/clusterConfiguration/dns/imageTag", "value": "my-new-version"}]'`?

**Comment by chuckha** [comment]
it's a little hard to use imo but we can definitely improve it moving forward, not a blocker at all

**Comment by ncdc** [comment]
Yeah... I'm thinking we go ahead and implement #38 😄

**Comment by chuckha** [comment]
#38 first then this sounds great to me 🚀

**Comment by ncdc** [comment]
@williamsandrew do you have a preference for jsonpatch vs something like `--machine-infra-patch spec.clusterConfiguration.dns.imageTag=my-new-version --machine-infra-patch spec.clusterConfiguration.etcd.imageTag=my-new-version2`?

**Comment by williamsandrew** [comment]
I have a slight preference towards individual flags but I imagine that may result in an explosion of flags. I think the flags are a better user experience. But that's not a deal breaker to me as long as the upgrade tool gives me a decent error message when my JSONPatch can't be applied.

**Comment by ncdc** [comment]
I went with json patch in #105. If you're in control of creating the data for Machine, infra machine, and KubeadmConfig, you should be able to tightly control and test the patches. The error message I got when testing out patching with a bad patch was decent-ish 😄 .
